---

# データベース作成
 - name : データベース作成
   postgresql_db: 
     name: "{{ pgsql_dbname }}"
     encoding: "UTF-8"
     login_user: postgres
   sudo_user: postgres
   sudo: yes

 #NOSUPERUSERをつけるとコケる。https://groups.google.com/forum/#!topic/ansible-project/-tDBSPtByfM
 - name: ユーザ作成
   postgresql_user: 
     db: "{{ pgsql_dbname }}"
     name: "{{ pgsql_dbuser }}"
     password: "{{ pgsql_dbpass }}"
     priv: ALL
     encrypted: yes
     state: present
     login_user: postgres
     role_attr_flags: "NOCREATEDB,NOCREATEUSER,NOCREATEROLE"
   sudo_user: postgres
   sudo: yes

