---
 - name: Get PostgreSQL Repo
   yum: name={{item}} state=present
   with_items:
     - http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm

 - name: DisabeRepo
   replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled=1" replace="enabled=0"
   with_items:
     - pgdg-94-centos.repo

 - name: Install PostgreSQL9.4 Server
   yum: name={{ item }} state=installed enablerepo=pgdg94
   with_items:
     - postgresql94-server
     - postgresql94
     - postgresql94-libs
     - python-psycopg2
   notify:
     - "start and enable pgsql94 on boot"

 - name: "initdb PostgreSQLl94"
   shell: /usr/pgsql-9.4/bin/initdb -D /var/lib/pgsql/9.4/data/
          creates=/var/lib/pgsql/9.4/data/postgresql.conf
   sudo_user: postgres
   sudo: yes

 - name: ローカルホストからの接続を許可94
   lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
     regexp='^#?listen_addresses\s*='
     line="listen_addresses = '127.0.0.1'"
     state=present
   notify: "restart pgsql94"

 - name: "Start PostgreSQLl94"
   service: name=postgresql-9.4 state=running

 - include: create.yml


 - name: pg_hba設定展開
   template:
     src: pg_hba.conf.j2 
     dest: /var/lib/pgsql/9.4/pg_hba.conf
     mode: 0600
     owner: postgres
     group: postgres
   notify: "restart pgsql94"
   tags:
    - postgres94

