---
# This playbook contains common plays that will be run on all nodes.

- name: yum update
  yum: name=* state=latest
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: Install libselinux-python 
  yum: name=libselinux-python state=present
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: Install ntp 
  yum: name=ntp state=present
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: Disable Selinux
  sudo: yes
  selinux: state=disabled
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: stop iptabes
  service: name=iptables state=stopped enabled=no
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

- name: stop firewalld
  service: name=firewalld state=stopped enabled=no
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95


- name: Get EPEL Repo
  yum: name={{item}} state=present
  with_items:
    - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95


- name: DisabeRepo
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled=1" replace="enabled=0"
  with_items:
    - epel.repo
    - remi.repo
  tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95
