---
# 初期設定

 - name: タイムゾーンをJSTにする
   shell: timedatectl set-timezone Asia/Tokyo
   tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

 - name: タイムゾーンをJSTにするその２
   template:
     src: clock.j2
     dest: /etc/sysconfig/clock
     owner: root
     group: root
     mode: 0644
   tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95

 - name: ホスト名設定
   sudo: true
   hostname:
     name: "{{ host_name }}"
   tags:
    - mysql55
    - mysql56
    - php54
    - php56
    - php70
    - postgres92
    - postgres94
    - postgres95
